### ISSUE TITLE
disable VndErrorExceptionListener in debug mode

### ISSUE THREAD

**Issue by VSilantyev** [kleijnweb/swagger-bundle#77]
I agree, this listener, logref part is the cool feature for production.
However, it slows down my local development, I should dig into logs for each exception, when I could have symfony web profiler right here, in the response.

I would like to implement it as an option in config.yml:

```
swagger:
  verbose_exceptions: %kernel.debug% # default false
```

What do you think about this feature?
Will you accept this pull request?

**Comment by kleijnweb** [comment]
Sure, as long as it is accompanied by Unit Tests and a doc update :)

**Comment by kleijnweb** [comment]
Closing this. I will accept PRs for 3.x, but I am not developing new features myself for that branch.
